name: 'CTAN submit'
description: 'Performs a submit on the CTAN API to validate or upload a package'
inputs:
  version:
    required: false
  action:
    required: false
    default: 'validate'
  fields:
    required: true
  file_path:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
