name: nightly
on:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  real:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: paolobrasolin/ctan-submit@master
      with:
        file_path: htunk.zip
        fields: |
          pkg: htunk
          version: 0.1.0
          author: Paolo Brasolin
          email: paolo.brasolin@gmail.com 
          uploader: paolo.brasolin@gmail.com 
          license: mit
          summary: This is a CI test
